version: "3.8"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/blog
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./:/var/www/blog
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - ${PMA_CONTAINER_PORT}:80
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  data:
###< doctrine/doctrine-bundle ###
